//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_chan_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int maHD { get; set; }
        public Nullable<int> maKH { get; set; }
        public Nullable<int> tongtien { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
    
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
