//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_chan_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int maKH { get; set; }
        public string tenKH { get; set; }
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sdt { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
