//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A_chan_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCuaHang
    {
        public string tenCH { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string website { get; set; }
    }
}
